### ISSUE TITLE
Amplitude of BHPTNR surrogate doesn't match that of of other waveforms for q <= 50 and also upto 1000.

### ISSUE THREAD

**Issue by bhooshan-gadre** [BlackHolePerturbationToolkit/BHPTNRSurrogate#3]
For q < 50, I tested BHPTNR surrogate against a few waveform approximants available in the lalsuite.
I see that there can be a huge discrepancy between BHPTNR surrogate amplitude and that of `IMRPhenomD`, `IMRPhenomXAS` and `SEOBNRv4` for q in range (10, 50) and total mass in range 1, 100. 
Even when I compare the two waveforms in the same frequency band, the amplitudes do not match.

As the mass ratio grows, SEON and Phenom waveform models differ slightly but not as much as BHPTNR surrogate.

With `IMRPhenomXAS, I did compare the amplitudes till q = 1000, but they differ by orders of magnitude. I only compared lmax = 2 modes. Even though the amplitudes do not match, the matches between the waveforms are not too bad (sub per cent to ~10% per cent).  This tells me that the geometric to SI scaling may be the issue but I could not locate the pattern. 

I was trying to use BHPTNR surrogate waveforms as injections in IMRI-sub-solar mass searches which I am currently pursuing.

**Comment by sfield17** [comment]
@bhooshan-gadre This appears to be due to a bug in gwtools when calling the geo_to_si function. The latest version of gwtools (1.1.6) fixed the bug. 

If this fixes your problem, we can close out this issue.

**Comment by bhooshan-gadre** [comment]
@sfield17 I don't think pc --> 1e6 * PC actually fixed the big. It has made it even worse. BHPTNRSurrogate SNR/amplitude was constantly lower than other waveform models by ~2-3 orders of magnitude. But now it has even gone down further by 6 orders of magnitude!

**Comment by sfield17** [comment]
gwtools 1.1.7 fixes the issue.
