### ISSUE TITLE
No h5 file and Zenodo link broken

### ISSUE THREAD

**Issue by LeanneDurkan** [BlackHolePerturbationToolkit/BHPTNRSurrogate#4]
No h5 file appears in the data folder, and I receive and error when I click on the link to the data via Zenodo.

**Comment by DeveshGiri** [comment]
change it to the following, and it should work fine
`wget https://zenodo.org/records/7125742/files/BHPTNRSur1dq1e4.h5`

**Comment by sfield17** [comment]
I wasn't able to reproduce this issue on my laptop running Ubuntu. I'm going to close out this issue, but if data download issues continue, please let me know your OS.

**Comment by sfield17** [comment]
I wasn't able to reproduce this issue on my laptop running Ubuntu. I'm going to close out this issue, but if data download issues continue, please let me know your OS.
