### ISSUE TITLE
Missing line in README

### ISSUE THREAD

**Issue by ekwessel** [BlackHolePerturbationToolkit/BHPTNRSurrogate#7]
I'm currently going through the README and I noticed that at the very beginning it says to git clone the repo and then run two git submodule commands. However, in order for these to run, one must cd into the recently cloned repository. It's a minor detail, but it might help less experienced users follow the instructions to include an instruction to cd into the repo directory after the initial clone in that section.

**Comment by sfield17** [comment]
Thanks for raising this issue. I've updated the README accordingly.
